name: Lake Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: leanprover/lean-action@v1
        with:
          build: true
          use-github-cache: true
          use-mathlib-cache: true
